default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: restaurant-reviews_development

test:
  <<: *default
  database: restaurant-reviews_test

production:
  <<: *default
  database: restaurant-reviews_production
  username: restaurant-reviews
  password: <%= ENV['RESTAURANT-REVIEWS_DATABASE_PASSWORD'] %>
